#!/bin/bash 
# Apple Beta Seeds Program 
sudo /System/Library/PrivateFrameworks/Seeding.Framework/Versions/A/Resources/seedutil enroll DeveloperSeed 
sudo softwareupdate --list-full-installers
sudo /System/Library/PrivateFrameworks/Seeding.Framework/Versions/A/Resources/seedutil unenroll
sudo /System/Library/PrivateFrameworks/Seeding.Framework/Versions/A/Resources/seedutil enroll PublicSeed 
sudo softwareupdate --list-full-installers
sudo /System/Library/PrivateFrameworks/Seeding.Framework/Versions/A/Resources/seedutil unenroll
sudo softwareupdate --list-full-installers
