#!/bin/bash

# Apple Program for Daily Production

# An overview for Apple Beta Program, Microsoft's Insider Program alternative:

# Apple releases macOS every year which complies software as a service , shorthand SaaS, basis. Before softwares released officially, they have alpha and beta versions before comes the release that's official for production.
# So, for Apple, they have 3 Apple Seed Programs for choices to us. The Seeds are:
# Regular
# PublicSeed
# DeveloperSeed

# You recieve the builds with first priority If you select either 1 of 2 seed programs insteading "Regular", means the builds numbers higher than regular builds usually for production.

# We explain the 3 Apple Seed Programs and how they works.

# Regular, aka Regular Seed:
# This is default seed when Apple devices once manufactured. And it uses this seed for daily production purposes. This seed also used for GitHub Actions by default.

# PublicSeed, aka Public Beta Seed:
# That's the beta seed which used for up to 75% of users if you have an Apple ID and registered the Apple Public Beta Program.
# Once you registered the program, you will recieve beta builds but have no developer tools and only for general testing purpose before rolling out officially. And that's only seed to public for free of charge.

# DeveloperSeed, aka Developer Seed Offical:
# That's beta seed for developers which allows downloading most lots of developer tools in macOS.
# You should apply an Apple developer ID with your Apple ID and if you pay USD$99 annually for premium access, including downloading that seed program's beta builds.
# Users with Apple Developer ID, once downloaded and installed these of builds, you will recieve developer community support by Apple only.

# This creation script is default to Developer Seed while generating installation disk.

# Side note 1: How to enroll your Apple Devices to your suitable Apple Seed Program? 
# A. If you have an Apple ID, please follow the instructions below:
# Recommend option by Apple Inc.
# 1. Head to https://beta.apple.com or https://developer.apple.com.
# 2. Signin or Singup your Apple ID.
# 3. Either Apple's Public Beta or Developer Beta Program, must agree the releative ToS and following instructions on screen, if you are new to Apple Beta Program. Prepare your bank card with sufficient balance quota for developer premium ID registration. This is your main payment method which used for annual subscription for Apple Developer ID. Or skip this step, if you are enrolled the Programs, already.
# 4. To gain your beta permission, download the automated tool by Apple to enroll your Apple device(s) (version 13.3 or eariler), or just signin your Apple ID (starting from version 13.4), by on-screen instructions.
# 5. Check your device update and recieve beta builds using Settings >> General >> Check device update >> Install if have beta builds. The on-screen instructions may depends your macOS, iOS and/or iPad OS versions.

# B. If you have local account on Apple device(s) only, means not applied Apple ID, you could only downloading Apple Developer Seed Program by Apple Package File. To proceed (Recommend by Mr. Poon's Studio) (Will deprecate soon):
# 1. Go to https://betaprofiles.com which are now shutdown by default. Click Join Community. It will leads to X Community.
# 2. Click the link provided by Community.
# 3. Select your Apple OS depends your Apple devices. e.g. MacBook Pro With Apple M series chips, scroll down to macOS and hit install profile.
# 4. Right click and copy the links if you need download with aria2c tool on Mac system or for other Apple's devices click install. It will download an automated tool backend from Apple.
# 5. Do the last 2 step mentioned in Part A.

# C. If you not eager to download anything and only run the script to enroll your Apple to either one of Apple Seed Programs, Do the following below (advanced users only and removed starting macOS 13.4):
# 1. Run these of commands with sudo privileges:
# sudo /System/Library/PrivateFraemworks/Seeding.Framework/Versions/A/Resources/seedutil enroll YourSeedNeedToEnroll
# 2. Enter your macOS local administrator account password when asked and you may need to restart your macOS.
# 3. Do the last 2 step mentioned in Part A.

# Side note 2: Leave the program from your Apple device(s):
# To leave the program by Apple device(s), follow the procedures below:
# 1. From the Apple menu in the corner of your screen:
# 2. Choose System Preferences. Then click Software Update.
# 3a. Click details and restore defaults, under "The macOS is enrolled in the Apple Seed Program.", or click cancel to remain current state, to confirm your choice (macOS 13.3 or earier).
# 3b. Reinstall macOS to go back Regular Seed by rebooting your Mac machine with key combination.

# In this automated file uses in GitHub Actions. It defaults to Apple Program for Daily Production. And designed for Github macOS 12 runner. We are enquiring Apple for solution, on how to acquiring Apple ID login credential along with macOS 13.4 powered GitHub Actions.

sudo softwareupdate --fetch-full-installer --agree-to-license
sudo hdiutil create -o ~/Desktop/macOS\ 14\ Installation\ Disk -size 20g -volname macOS\ 14\ Installation\ Disk -layout GUID -fs APFS -format UDBZ -tasks 16 -attach
sudo /Applications/Install\ macOS\ 14\ beta.app/Contents/Resources/createinstallmedia --volume /Volumes/Install\ macOS\ 14 --nointeraction
sudo hdiutil detach /Volumes/macOS\ 14\ Installation\ Disk
sudo hdiutil convert ~/Desktop/macOS\ 14\ Installation\ Disk -format UDTO -o ~/Desktop/macOS\ 14\ Beta\ Installation\ Disk.iso
sudo hdiutil convert ~/Desktop/macOS\ 14\ Installation\ Disk -format UDRO -o ~/Desktop/macOS\ 14\ Beta\ Installation\ Disk.dmg
