#!/bin/bash

# Apple Program for Daily Production

# An overview for Apple Beta Program, Microsoft's Insider Program alternative:

# Apple releases macOS every year which complies software as a service , shorthand SaaS, basis. Before softwares released officially, they have alpha and beta versions before comes the release that's official for production.
# So, for Apple, they have 3 Apple Seed Programs for choices to us. The Seeds are:
# Regular
# PublicSeed
# DeveloperSeed

# You recieve the builds with first priority If you select either 1 of 2 seed programs insteading "Regular", means the builds numbers higher than regular builds usually for production.

# We explain the 3 Apple Seed Programs and how they works.

# Regular, aka Regular Seed:
# This is default seed when Apple devices once manufactured. And it uses this seed for daily production purposes. This seed also used for GitHub Actions by default.

# PublicSeed, aka Public Beta Seed:
# That's the beta seed which used for up to 75% of users if you have an Apple ID and registered the Apple Public Beta Program.
# Once you registered the program, you will recieve beta builds but have no developer tools and only for general testing purpose before rolling out officially. And that's only seed to public for free of charge.

# DeveloperSeed, aka Developer Seed Offical:
# That's beta seed for developers which allows downloading most lots of developer tools in macOS.
# You should apply an Apple developer ID with your Apple ID and if you pay USD$99 annually for premium access, including downloading that seed program's beta builds.
# Users with Apple Developer ID, once downloaded and installed these of builds, you will recieve developer community support by Apple only.

# This creation script in GitHub Actions defaults generating all types of installation disk.

# Side note 1: How to enroll your Apple Devices to your suitable Apple Seed Program? 
# A. Must have your Apple ID, and follow the instructions below:
# Recommend option by Apple Inc.
# 1. Head to https://beta.apple.com or https://developer.apple.com.
# 2. Signin or Singup your Apple ID.
# 3. Either Apple's Public Beta or Developer Beta Program, must agree the releative ToS and following instructions on screen, if you are new to Apple Beta Program. Prepare your bank card with sufficient balance quota for beta premium ID registration, or just sign in and finished on browser. This is your main payment method which used for annual subscription for Apple Developer ID. Or skip this step, if you are enrolled the Programs, already.
# 4. Spotlight search "Software Update", then switch to one of Apple Beta Program enrolling your Apple device(s) (starting from version 13.4), Or, Install Beta Profile download from Apple. May reboot your device (macOS 13.3 eariler).
# 5. Check your device update and recieve beta builds using Settings >> General >> Check device update >> Install if have beta builds. The on-screen instructions may depends your macOS, iOS and/or iPad OS versions.

# B. You could joining Apple Beta Program by downloading Apple Beta Profile with local account on Apple device(s), not Apple ID signed-in, only. Proceeding (Recommend by Mr. Poon's Studio) (Deprecated on macOS 13.4 and further):
# 1. To https://betaprofiles.com which are now shutdown by default. Click Join Community. It leads one of valid X Community.
# 2. Click the link provided by Community.
# 3. Select your Apple OS depends your Apple devices. e.g. MacBook Pro With Apple M series chips, scroll down to macOS and hit install profile.
# 4. Right click and copy the link, download with aria2c tool on Mac system or for other Apple's devices. double click downloaded file and profile install. It automates with seedutil.
# 5. Do the last step mentioned in Part A.

# C. Do the following below by running the script, enrolling you either one of Apple Seed Programs, if you not eagering joining anything (advanced users only and starting macOS 13.4):
# 1. Run these of commands:
# sudo defaults write com.apple.SoftwareUpdate CatalogURL
# defaults write com.apple.SoftwareUpdate CatalogURL
# - with either one URL exampled:
# "https://swscan.apple.com/content/catalogs/others/index-14seed-14-13-12-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.gz"
# "https://swscan.apple.com/content/catalogs/others/index-14beta-14-13-12-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.gz"
# 2. Enter your macOS local administrator account password when asked with sudo mode and you may need to restart your macOS.
# 3. Do the last step mentioned in Part A.

# Side note 2: Leave the program from your Apple device(s):
# To leave the program by Apple device(s), follow the procedures below:
# 1. From the Apple menu in the corner of your screen:
# 2. Choose System Preferences. Then click Software Update.
# 3a. Click details and restore defaults, under "The macOS is enrolled in the Apple Seed Program.", or click cancel to remain current state, to confirm your choice (macOS 13.3 or earier).
# 3b. Change back "Regular" once may shown in seeds selection and wait for next official stable release, while you signed-in your Apple ID in Mac device (macOS 13.4 further).
# 3c. Run "(sudo) defaults write com.apple.SoftwareUpdate CatalogURL" in macOS Terminal using example URL by following with all both users and root:
# "https://swscan.apple.com/content/catalogs/others/index-14-13-12-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.gz"

# In this automated file uses in GitHub Actions. It defaults to Apple Program for Daily Production. And designed for Github macOS 13 runner. 

sudo defaults write com.apple.SoftwareUpdate CatalogURL "lhttps://swscan.apple.com/content/catalogs/others/index-14-13-12-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.gz
defaults write com.apple.SoftwareUpdate CatalogURL https://swscan.apple.com/content/catalogs/others/index-14-13-12-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.gz
sudo softwareupdate --fetch-full-installer --full-installer-version 14 --agree-to-license --force
sudo hdiutil create -o ~/Desktop/macOS\ 14\ Installation\ Disk -size 20g -volname macOS\ 14\ Installation\ Disk -layout GUID -fs APFS -format UDBZ -tasks 16 -attach
sudo /Applications/Install\ macOS\ 14\ beta.app/Contents/Resources/createinstallmedia --volume /Volumes/Install\ macOS\ 14 --nointeraction
sudo hdiutil detach /Volumes/macOS\ 14\ Installation\ Disk
sudo hdiutil convert ~/Desktop/macOS\ 14\ Installation\ Disk -format UDTO -o ~/Users/runners/macOS\ 14\ Beta\ Installation\ Disk.iso
sudo hdiutil convert ~/Desktop/macOS\ 14\ Installation\ Disk -format UDRO -o ~/Users/runners/macOS\ 14\ Beta\ Installation\ Disk.dmg
sudo rm -rf /Application/Install*.app
