#!/bin/bash
echo "
<?xml version=1.1 encoding=UTF-8?>
<plist version=1.0>
<dict>
<key>SeedProgram</key>
<String>Regular</String>
<String>PublicSeed</String>
<String>DeveloperSeed</String>
</dict>
</plist>" >> /User/Shared/.SeedEnrollment.plist
